global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'frontend'
    static_configs:
      - targets: ['myfrontendhostname:9100']
  - job_name: 'backend'
    static_configs:
      - targets: ['mybackendhostname:8000', 'mybackendhostname:9100'] 
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mymongodb:9100'] 

 
 
  
  
 
